@baseUrl = http://localhost:5268

###
# @name Run seed
GET {{baseUrl}}/seed
Content-Type: application/json

###
# @name Get pokemons 
GET {{baseUrl}}/pokemon
Content-Type: application/json

###
# @name Get pokemons with pagination
GET {{baseUrl}}/pokemonWithPagination?pageNumber=1&pageSize=10
Content-Type: application/json