version: "3.9"

services:
  webui:
    container_name: pokemon-webui
    build:
      context: ./src/WebUI
      dockerfile: ./Dockerfile
    depends_on:
      - api
    ports:
      - 4200:80
    # volumes:
    #   - ./angular:/project
    #   - /project/node_modules
  api:
    container_name: pokemon-api
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    ports:
      - 5268:8080
      - 7114:443
    environment:
      - DOTNET_VERSION=8.0.0
      - DOTNET_DOWNLOAD_URL=https://dotnetcli.azureedge.net/dotnet/Runtime/8.0.0/dotnet-runtime-8.0.0-linux-x64.tar.gz
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    
  postgres:
    container_name: database-pokemon-pg
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # PGDATA: /data/postgres
    volumes:
    - ./data/postgres:/data/postgres
    - ./data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
